name: loading_provider
description: "Flutter package for easily displaying loading overlays with customizable configurations."
version: 0.0.9
homepage: https://github.com/amitzero/loading_provider.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


